#!/bin/sh
#
# Start application....
#

start() {
    printf "Starting App: "
    mkdir -p /mnt/tfcard
    mount /dev/mmcblk0p1 /mnt/tfcard
    mkdir -p /mnt/mmc
    modprobe tsc2007
    /opt/flashtool/flashtool
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
